"""fix: search filters, runBrainSearch order, API_BASE same-origin

Revision ID: dbf3673ad2a0
Revises: f8ab031fadd6
Create Date: 2026-09-01 18:10:09.870039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbf3673ad2a0'
down_revision: Union[str, None] = 'f8ab031fadd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_diocesepresentation')
    op.drop_table('django_content_type')
    op.drop_index('announcements_comment_announcement_id_c673e2d5', table_name='announcements_comment')
    op.drop_index('announcements_comment_parent_id_20c2a808', table_name='announcements_comment')
    op.drop_index('announcements_comment_user_id_db28c264', table_name='announcements_comment')
    op.drop_table('announcements_comment')
    op.drop_table('pages_teammember')
    op.drop_table('testimonials_testimonial')
    op.drop_table('announcements_announcement')
    op.drop_table('pages_paroissespresentation')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    op.drop_table('django_session')
    op.drop_index('ministries_ministryactivity_ministry_id_c9eb60be', table_name='ministries_ministryactivity')
    op.drop_table('ministries_ministryactivity')
    op.drop_index('sermons_sermon_category_id_2bcbb172', table_name='sermons_sermon')
    op.drop_index('sermons_sermon_slug_48ad467c_like', table_name='sermons_sermon')
    op.drop_table('sermons_sermon')
    op.drop_index('announcements_announcementimage_announcement_id_e228fb8b', table_name='announcements_announcementimage')
    op.drop_table('announcements_announcementimage')
    op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('settings_sitesettings')
    op.drop_index('sermons_sermoncategory_slug_e21d91b2_like', table_name='sermons_sermoncategory')
    op.drop_table('sermons_sermoncategory')
    op.drop_table('pages_contactmessage')
    op.drop_table('pages_timelineevent')
    op.drop_table('ministries_ministrypage')
    op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('pages_missionaxe')
    op.drop_table('django_migrations')
    op.drop_table('pages_visionvalue')
    op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index('api_messages_message_recipient_id_ad50adc6', table_name='api_messages_message')
    op.drop_index('api_messages_message_sender_id_d90c9954', table_name='api_messages_message')
    op.drop_table('api_messages_message')
    op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_index('accounts_account_phone_number_49694350_like', table_name='accounts_account')
    op.drop_table('accounts_account')
    op.drop_table('ministries_ministry')
    op.drop_table('parishes_parish')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parishes_parish',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('zone', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('faithful', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('pastor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='parishes_parish_pkey')
    )
    op.create_table('ministries_ministry',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('testimony_author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mission_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mission_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('testimony_quote_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('testimony_quote_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ministries_ministry_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('accounts_account',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('otp_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('otp_expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('email_validated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='accounts_account_user_id_d61b40c6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='accounts_account_pkey'),
    sa.UniqueConstraint('phone_number', name='accounts_account_phone_number_key'),
    sa.UniqueConstraint('user_id', name='accounts_account_user_id_key')
    )
    op.create_index('accounts_account_phone_number_49694350_like', 'accounts_account', ['phone_number'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('api_messages_message',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['auth_user.id'], name='api_messages_message_recipient_id_ad50adc6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['auth_user.id'], name='api_messages_message_sender_id_d90c9954_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='api_messages_message_pkey')
    )
    op.create_index('api_messages_message_sender_id_d90c9954', 'api_messages_message', ['sender_id'], unique=False)
    op.create_index('api_messages_message_recipient_id_ad50adc6', 'api_messages_message', ['recipient_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key')
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('pages_visionvalue',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pages_visionvalue_pkey')
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('pages_missionaxe',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('text_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('text_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pages_missionaxe_pkey')
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('ministries_ministrypage',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('hero_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hero_badge_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hero_badge_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hero_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ministries_ministrypage_pkey')
    )
    op.create_table('pages_timelineevent',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pages_timelineevent_pkey')
    )
    op.create_table('pages_contactmessage',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pages_contactmessage_pkey')
    )
    op.create_table('sermons_sermoncategory',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sermons_sermoncategory_pkey'),
    sa.UniqueConstraint('slug', name='sermons_sermoncategory_slug_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('sermons_sermoncategory_slug_e21d91b2_like', 'sermons_sermoncategory', ['slug'], unique=False)
    op.create_table('settings_sitesettings',
    *[sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contact_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('facebook_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('youtube_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('instagram_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('twitter_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('whatsapp_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hero_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hero_subtitle_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('about_content_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_content_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('about_content_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_content_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hero_subtitle_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hero_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bible_verse_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bible_verse_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bible_verse_ref_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bible_verse_ref_fr', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('btn_emissions_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('btn_emissions_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('btn_meditation_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('btn_meditation_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('btn_teachings_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('btn_teachings_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_categories_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_categories_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_categories_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_categories_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_featured_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_featured_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stat_audience_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stat_audience_fr', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stat_emissions_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stat_emissions_fr', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stat_languages_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stat_languages_fr', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('background_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('body_font', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('body_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('heading_font', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('heading_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('primary_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('secondary_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('small_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('subheading_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('text_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('footer_contact_title_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('footer_contact_title_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('footer_copyright_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('footer_copyright_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('footer_description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('footer_description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('footer_quick_links_title_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('footer_quick_links_title_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('footer_social_title_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('footer_social_title_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('header_admin_btn_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('header_admin_btn_fr', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('header_slogan_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('header_slogan_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('show_admin_button', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('page_about_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_about_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_contact_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('page_contact_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('page_courses_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('page_courses_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hero_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stat_audience_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stat_emissions_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stat_languages_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('about_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_title_accent_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('about_title_accent_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('about_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('about_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contact_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contact_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_announcements_accent_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_announcements_accent_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_announcements_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_announcements_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_announcements_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_announcements_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_announcements_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('section_announcements_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('section_categories_accent_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_categories_accent_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_featured_accent_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_featured_accent_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_featured_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_featured_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_featured_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_featured_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_accent_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_accent_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('section_testimonials_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('about_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quote_author_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quote_author_name_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('quote_author_name_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('quote_author_subtitle_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('quote_author_subtitle_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('quote_text_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quote_text_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stat_years_label_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stat_years_label_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stat_years_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('team_description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('team_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('team_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('about_feature1_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_feature1_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_feature2_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_feature2_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_feature3_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_feature3_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_feature4_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('about_feature4_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bishop_bio_p1_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bishop_bio_p2_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('diocese_subtitle_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('history_intro_text_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('history_intro_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('history_subtitle_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mission_intro_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_subtitle_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_text_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item1_cta_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('engage_item1_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item1_href', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('engage_item1_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('engage_item1_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_item2_cta_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('engage_item2_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item2_href', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('engage_item2_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('engage_item2_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_item3_cta_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('engage_item3_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item3_href', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('engage_item3_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('engage_item3_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parishes_map_stats_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_map_subtitle_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_map_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_pillar1_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_pillar1_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vision_pillar1_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_pillar2_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_pillar2_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vision_pillar2_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_pillar3_desc_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_pillar3_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vision_pillar3_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item1_cta_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('engage_item1_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item1_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_item2_cta_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('engage_item2_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item2_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_item3_cta_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('engage_item3_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engage_item3_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parishes_map_stats_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_map_subtitle_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_map_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('parishes_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_pillar1_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_pillar1_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_pillar2_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_pillar2_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_pillar3_desc_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_pillar3_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('engage_bg_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('footer_brand_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('footer_brand_subtitle', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('parishes_bg_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stat_audience_desc_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stat_audience_desc_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stat_emissions_desc_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stat_emissions_desc_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stat_languages_desc_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stat_languages_desc_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stat_years_desc_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stat_years_desc_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stats_cta_href', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stats_cta_link_text_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stats_cta_link_text_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stats_cta_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stats_cta_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stories_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stories_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stories_bg_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stories_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stories_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_bg_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hero_badge_en', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('hero_badge_fr', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('hero_btn1_link_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hero_btn1_link_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hero_btn1_text_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hero_btn1_text_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hero_btn2_link_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hero_btn2_link_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hero_btn2_text_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hero_btn2_text_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('default_language', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('parishes_badge_en', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('parishes_badge_fr', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('diocese_name_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('bishop_bio_p1_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bishop_bio_p2_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('diocese_name_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('diocese_subtitle_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('history_intro_text_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('history_intro_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('history_subtitle_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mission_intro_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_subtitle_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vision_text_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('info_message_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('info_message_link', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('info_message_text_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('info_message_text_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bishop_message_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bishop_message_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bishop_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('bishop_photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bishop_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('bishop_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('history_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('history_text_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('history_text_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('history_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('history_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mission_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mission_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mission_description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mission_description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mission_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mission_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mission_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('nav_bishop_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_bishop_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_history_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_history_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_team_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_team_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_vision_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_vision_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('organization_subtitle_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('organization_subtitle_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('organization_text_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('organization_text_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('organization_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('organization_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('team_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('team_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('values_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('values_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('values_description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('values_description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('values_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('values_title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('values_title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('vision_badge_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vision_badge_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vision_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nav_about_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_about_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_contact_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_contact_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_home_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_home_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_news_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nav_news_fr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('info_badge_text_en', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('info_badge_text_fr', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='settings_sitesettings_pkey')]
    )
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('announcements_announcementimage',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('announcement_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements_announcement.id'], name='announcements_announ_announcement_id_e228fb8b_fk_announcem', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='announcements_announcementimage_pkey')
    )
    op.create_index('announcements_announcementimage_announcement_id_e228fb8b', 'announcements_announcementimage', ['announcement_id'], unique=False)
    op.create_table('sermons_sermon',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preacher_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('video_file', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('audio_file', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sermon_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('document_file', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_fr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language_primary', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.CheckConstraint('duration_minutes >= 0', name='sermons_sermon_duration_minutes_check'),
    sa.CheckConstraint('views_count >= 0', name='sermons_sermon_views_count_f97dc593_check'),
    sa.ForeignKeyConstraint(['category_id'], ['sermons_sermoncategory.id'], name='sermons_sermon_category_id_2bcbb172_fk_sermons_s', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='sermons_sermon_pkey'),
    sa.UniqueConstraint('slug', name='sermons_sermon_slug_key')
    )
    op.create_index('sermons_sermon_slug_48ad467c_like', 'sermons_sermon', ['slug'], unique=False)
    op.create_index('sermons_sermon_category_id_2bcbb172', 'sermons_sermon', ['category_id'], unique=False)
    op.create_table('ministries_ministryactivity',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ministry_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries_ministry.id'], name='ministries_ministrya_ministry_id_c9eb60be_fk_ministrie', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='ministries_ministryactivity_pkey')
    )
    op.create_index('ministries_ministryactivity_ministry_id_c9eb60be', 'ministries_ministryactivity', ['ministry_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('pages_paroissespresentation',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('hero_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hero_badge_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_subtitle_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_badge_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_subtitle_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pages_paroissespresentation_pkey')
    )
    op.create_table('announcements_announcement',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('content_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('title_fr', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='announcements_announcement_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('testimonials_testimonial',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='testimonials_testimonial_pkey')
    )
    op.create_table('pages_teammember',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pages_teammember_pkey')
    )
    op.create_table('announcements_comment',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('author_email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('announcement_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('likes >= 0', name='announcements_comment_likes_check'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements_announcement.id'], name='announcements_commen_announcement_id_c673e2d5_fk_announcem', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['announcements_comment.id'], name='announcements_commen_parent_id_20c2a808_fk_announcem', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='announcements_comment_user_id_db28c264_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='announcements_comment_pkey')
    )
    op.create_index('announcements_comment_user_id_db28c264', 'announcements_comment', ['user_id'], unique=False)
    op.create_index('announcements_comment_parent_id_20c2a808', 'announcements_comment', ['parent_id'], unique=False)
    op.create_index('announcements_comment_announcement_id_c673e2d5', 'announcements_comment', ['announcement_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq')
    )
    op.create_table('pages_diocesepresentation',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('history_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bishop_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bishop_photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hero_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bishop_message_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bishop_message_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('history_text_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('history_text_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_text_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_text_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_subtitle_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_subtitle_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vision_description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vision_description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vision_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vision_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('history_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('history_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vision_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mission_description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mission_description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mission_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mission_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mission_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('values_description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('values_description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('values_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('values_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('values_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('team_badge_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('team_badge_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('team_description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team_description_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('team_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bishop_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bishop_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mission_badge_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mission_badge_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('organization_subtitle_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('organization_subtitle_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('organization_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('organization_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('values_badge_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('values_badge_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vision_badge_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vision_badge_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_title_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hero_title_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_bishop_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_bishop_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_history_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_history_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_team_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_team_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_vision_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nav_vision_fr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pages_diocesepresentation_pkey')
    )
    # ### end Alembic commands ###
